name: Build

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, clang, cl]
        cpp_compiler: [gcc, clang, cl]
        target: [x64, arm64]

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Upload minesweeper-${{ matrix.target }}
      uses: actions/upload-artifact@v3
      with:
        name: minesweeper-${{ matrix.target }}.zip
        path: target/{{ matrix.target }}/release/minesweeper-${{ matrix.target }}.zip

    - name: Publish in release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: |
          target/${{ matrix.target }}/release/minesweeper-${{ matrix.target }}.zip
        token: ${{ secrets.GITHUB_TOKEN }}
